# -*- coding: utf-8 -*-
"""Brownian  motion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQeqZJHQFQq_5HdWew4oUVIsnEYlzT-6

**BROWNIAN MOTION**

It is a  mathematical model of random continuous function.

**Key properties:**

Let W(t) be Brownian motion:

1.**Starts at zero**

W(0)=0

2.**Independent increments**

Motion in different time intervals is independent

3.**Gaussian increments**

W(t)−W(s)∼N(0,t−s)  ,0<s<t

**Discrete approximation for simulation**


W(t+dt)=W(t) + N(0,dt)
"""

import numpy as np
import matplotlib.pyplot as plt

# Parameters
total_time = 1.0
num_steps = 1000
dt = total_time / num_steps

# Generate standard normal random steps
# Scale by sqrt(dt) to get the correct variance
steps = np.random.normal(0, np.sqrt(dt), num_steps)

# Calculate cumulative sum to get the Brownian path (add starting point of 0)
brownian_path = np.zeros(num_steps + 1)
brownian_path[1:] = np.cumsum(steps)
print(brownian_path)
print(len(brownian_path))
# Time array
time = np.linspace(0, total_time, num_steps + 1)
print(time)

# Plotting the path
plt.plot(time, brownian_path)
plt.title('Simulated Brownian Motion')
plt.xlabel('Time')
plt.ylabel('W(t)')
plt.show()


#plotting multiple paths
num_paths = 5

plt.figure()

for _ in range(num_paths):
    steps = np.random.normal(0, np.sqrt(dt), num_steps)
    brownian_path = np.zeros(num_steps + 1)
    brownian_path[1:] = np.cumsum(steps)
    plt.plot(time, brownian_path)

plt.title("Multiple Brownian Motion Paths")
plt.xlabel("Time")
plt.ylabel("W(t)")
plt.show()